const assert=require('node:assert/strict'),P=require('../assets/pizzaria-core'),S=require('../assets/estado');
function prepared(){const p=P.fresh();P.newOrder(p,()=>0);assert(P.start(p));for(const [x,y] of P.CELLS){P.brush(p,'molho',{x,y});P.brush(p,'queijo',{x,y});}return p;}
let p=prepared();assert.equal(p.stock.massa,4);assert.equal(p.stock.molho,4);assert.equal(p.stock.queijo,4);assert.equal(p.active.sauce.length,P.CELLS.length);P.brush(p,'molho',{x:.5,y:.5});assert.equal(p.stock.molho,4);assert(!P.topping(p,'calabresa',{x:0,y:0}));assert.equal(p.stock.calabresa,3);
assert(!P.moveTo(p,'serve'));P.moveTo(p,'oven');P.moveTo(p,'baking');assert(!P.moveTo(p,'cut'));for(let i=0;i<8;i++)P.tick(p,1000);P.moveTo(p,'cut');assert(!P.cut(p,{x:.5,y:.5},{x:.7,y:.7}));
for(let i=0;i<3;i++){const a=i*Math.PI/3;assert(P.cut(p,{x:.5+Math.cos(a)*.44,y:.5+Math.sin(a)*.44},{x:.5-Math.cos(a)*.44,y:.5-Math.sin(a)*.44}));}assert(!P.cut(p,{x:.06,y:.5},{x:.94,y:.5}));P.moveTo(p,'serve');const before=p.cash,result=P.settle(p);assert.equal(result.score,100);assert.equal(result.tip,6);assert.equal(p.cash,before+22);assert.equal(p.served,1);assert.equal(P.settle(p),null);assert.equal(p.cash,before+22);
const perfect=result;p=prepared();P.topping(p,'calabresa',{x:.5,y:.5});p.active.bakeMs=19000;p.active.stage='serve';const bad=P.settle(p);assert(bad.score<perfect.score);assert(bad.pay<perfect.pay);assert.equal(bad.tip,0);
const saved=S.fresh();saved.pizzaria=p;const round=S.unpack(S.pack(saved)).state;assert.deepEqual(round.pizzaria,P.normalize(p));const old=S.fresh();delete old.pizzaria;const migrated=S.normalize(old);assert.equal(migrated.pizzaria.cash,30);assert.equal(migrated.fase,old.fase);
p=prepared();p.active.stage='baking';p.active.bakeMs=4567;const resumed=S.unpack(S.pack({...S.fresh(),pizzaria:p})).state.pizzaria;assert.equal(resumed.active.stage,'baking');assert.equal(resumed.active.bakeMs,4567);assert.deepEqual(resumed.stock,p.stock);
p=P.fresh();p.cash=0;p.stock.massa=0;P.newOrder(p);assert(!P.start(p));assert(!P.buy(p,'massa'));assert(P.help(p));assert(!P.help(p));assert(P.start(p));assert.equal(p.cash,0);assert(!P.buy(p,'__proto__'));assert(!P.topping(p,'__proto__',{x:.5,y:.5}));
p=P.fresh();const cash=p.cash;assert(P.buy(p,'queijo'));assert.equal(p.cash,cash-10);assert.equal(p.stock.queijo,10);p.stock.queijo=999;assert(!P.buy(p,'queijo'));
for(let n=0;n<100;n++){p=P.fresh();p.served=20;P.newOrder(p);P.start(p);const r=P.recipe(p.active.recipe);for(const [x,y]of P.CELLS){P.brush(p,'molho',{x,y});P.brush(p,'queijo',{x,y});}for(const kind of r.toppings)for(let i=0;i<6;i++)P.topping(p,kind,{x:.5+Math.cos(i*Math.PI/3)*.23,y:.5+Math.sin(i*Math.PI/3)*.23});p.active.bakeMs=8000;for(let i=0;i<p.active.slices/2;i++){const a=i*Math.PI/(p.active.slices/2);P.cut({...p,active:{...p.active,stage:'cut'}},{x:.5+Math.cos(a)*.44,y:.5+Math.sin(a)*.44},{x:.5-Math.cos(a)*.44,y:.5-Math.sin(a)*.44});}p.active.cuts=Array.from({length:p.active.slices/2},(_,i)=>i*Math.PI/(p.active.slices/2));assert.equal(P.evaluate(p.active).score,100);}
console.log('PASS: perfect/wrong orders, tips, inventory, drag bounds, cuts, duplicate settlement, restock, recovery, old saves and in-progress resume');
